# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: pose_one
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - right_shoulder_humerus
    - right_humerus_elbow
    - right_elbow_forearm
    - right_forearm_wristy
    - right_wristy_wristx
    - right_wristx_wristz
    - right_palm_index0
    - right_index0_index1
    - right_index1_index2
    - right_index2_index3
    - right_palm_middle0
    - right_middle0_middle1
    - right_middle1_middle2
    - right_middle2_middle3
    - right_palm_pinky0
    - right_pinky0_pinky1
    - right_pinky1_pinky2
    - right_pinky2_pinky3
    - right_palm_ring0
    - right_ring0_ring1
    - right_ring1_ring2
    - right_ring2_ring3
    - right_palm_thumb_zero
    - right_palm_thumb0
    - right_thumb0_thumb1
    - right_thumb1_thumb2
    - right_thumb2_thumb3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_shoulder_humerus
      - right_humerus_elbow
      - right_elbow_forearm
      - right_forearm_wristy
      - right_wristy_wristx
      - right_wristx_wristz
  - name: index_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_palm_index0
      - right_index0_index1
      - right_index1_index2
      - right_index2_index3
  - name: middle_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_palm_middle0
      - right_middle0_middle1
      - right_middle1_middle2
      - right_middle2_middle3
  - name: ring_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_palm_ring0
      - right_ring0_ring1
      - right_ring1_ring2
      - right_ring2_ring3
  - name: pinky_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_palm_pinky0
      - right_pinky0_pinky1
      - right_pinky1_pinky2
      - right_pinky2_pinky3
  - name: thumb_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_palm_thumb_zero
      - right_palm_thumb0
      - right_thumb0_thumb1
      - right_thumb1_thumb2
      - right_thumb2_thumb3